services:

#  application:
#    container_name: app
#    image: agrix-image
#    restart: always
#    ports:
#      - 8080:8080
#    links:
#      - mysql:database
#    environment:
#      - DATABASE_HOST=database
#      - DATABASE_PORT=3306
#      - DATABASE_USER=root
#      - DATABASE_PASSWORD=root

  mysql:
    image: mysql:8.0.32
    container_name: agrixdb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agrixdb