services:

  database:
    image: mysql:8.0.32
    container_name: agrixdb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agrixdb
